name: test

defaults:
  run:
    shell: bash

env:
  TERM: xterm-256color

on: [push]

jobs:
  lint-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
        with:
          submodules: true
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: run dockerized test
        uses: docker/build-push-action@v5.1.0
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: Dockerfile
          outputs: type=local,dest=/tmp/output/
          target: ci
      - name: print dockerized test output
        run: scripts/cat-all.sh /tmp/output/ --github

  deploy-to-github-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: pages
      cancel-in-progress: false
    needs: lint-and-test
    runs-on: ubuntu-22.04
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: checkout
        uses: actions/checkout@v4.1.1
        with:
          submodules: true
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: run dockerized build
        uses: docker/build-push-action@v5.1.0
        with:
          cache-from: type=gha
          context: .
          file: Dockerfile
          outputs: type=local,dest=/tmp/build/
          provenance: false
          target: build
      - name: upload built artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: /tmp/build/
      - name: setup github pages
        uses: actions/configure-pages@v4.0.0
      - name: deploy built artifact to github pages
        id: deployment
        uses: actions/deploy-pages@v4.0.4
